#ifndef VK_INSTANCE_LEVEL_FUNCTION
#define VK_INSTANCE_LEVEL_FUNCTION( fun )
#endif // !VK_INSTANCE_LEVEL_FUNCTION

VK_INSTANCE_LEVEL_FUNCTION(vkDestroyInstance)

VK_INSTANCE_LEVEL_FUNCTION(vkGetDeviceProcAddr)

VK_INSTANCE_LEVEL_FUNCTION(vkEnumeratePhysicalDevices)

#undef VK_INSTANCE_LEVEL_FUNCTION